#!/usr/bin/env python3

from lantex import types
from parser import LantexParser

if __name__ == "__main__":
    p = LantexParser('/home/liam/Documents/lantex/test.lan', trace=False)
    p.parse()
    print(p.entities)
