#!/usr/bin/env python3

from lantex.types import *
from lantex.drawing import Drawing
from parser import LantexParser
import logging

if __name__ == "__main__":
    loglevel = logging.INFO
    p = LantexParser('/home/liam/Documents/lantex/test.lan', False, loglevel)
    p.parse()
    d = Drawing('/home/liam/Documents/lantex/out.svg', p)
    d.render()
